### ISSUE TITLE
Another opentracing API breakage

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#338]
```
ugh ~/src/github.com/go-kit/kit/tracing (master) go test ./...
?       github.com/go-kit/kit/tracing   [no test files]
# github.com/go-kit/kit/tracing/opentracing_test
opentracing/grpc_test.go:22: beforeSpan.Context().SetBaggageItem undefined (type "github.com/opentracing/opentracing-go".SpanContext has no field or method SetBaggageItem)
opentracing/grpc_test.go:61: joinedSpan.Context().BaggageItem undefined (type "github.com/opentracing/opentracing-go".SpanContext has no field or method BaggageItem)
opentracing/http_test.go:22: beforeSpan.Context().SetBaggageItem undefined (type "github.com/opentracing/opentracing-go".SpanContext has no field or method SetBaggageItem)
opentracing/http_test.go:61: joinedSpan.Context().BaggageItem undefined (type "github.com/opentracing/opentracing-go".SpanContext has no field or method BaggageItem)
FAIL    github.com/go-kit/kit/tracing/opentracing [build failed]
```

**Comment by peterbourgon** [comment]
Broken by https://github.com/opentracing/opentracing-go/pull/106

**Comment by lordnynex** [comment]
@peterbourgon I'm seeing some errors today related to opentracing. I'm not sure if I'm doing something wrong or this should be opened in a new issue. 

```bash
$ godep get github.com/go-kit/kit/...
# github.com/go-kit/kit/tracing/opentracing
../../go-kit/kit/tracing/opentracing/http.go:39: undefined: opentracing.HTTPHeaderTextMapCarrier
../../go-kit/kit/tracing/opentracing/http.go:59: undefined: opentracing.HTTPHeaderTextMapCarrier
```

**Comment by basvanbeek** [comment]
@lordnynex check your go-kit repo if you have uncommitted changes as it seems your repository is out of date.

Current Go kit lines read:
https://github.com/go-kit/kit/blob/master/tracing/opentracing/http.go#L39
https://github.com/go-kit/kit/blob/master/tracing/opentracing/http.go#L59
